(Dialog ui_config
    (Components
        (SubLayout Content)
        (Separator CommitSeparator)
        (PushButton CommitOK)
        (PushButton CommitCancel)
    )
    (Resources
        (CommitSeparator.ResourceHints "Template:OKCancelDialog.CommitSeparator")
        (CommitOK.Label "Apply")
        (CommitOK.TopOffset 10)
        (CommitOK.BottomOffset 10)
        (CommitOK.LeftOffset 40)
        (CommitOK.RightOffset 0)
        (CommitOK.ResourceHints "Template:OKCancelDialog.CommitOK" "UserOverrideAttrs:Label,ButtonStyle")
        (CommitCancel.Label "Закрыть")
        (CommitCancel.TopOffset 10)
        (CommitCancel.BottomOffset 10)
        (CommitCancel.LeftOffset 8)
        (CommitCancel.RightOffset 10)
        (CommitCancel.ResourceHints "Template:OKCancelDialog.CommitCancel")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.DefaultButton "CommitOK")
        (.ResourceHints "Template:OKCancelDialog" "Guidelines:Creo4-Dialog" "GuidelinesVersion:1" "Version:Creo4" "@Subgrid0x2.Template:OKCancelDialog.CommitBar")
        (.Accelerator "Esc")
		(.Label "Settigs (by alex-levadnyy)")
        (.AttachLeft True)
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1)
                Content CommitSeparator
                (Grid
                    (Rows 1)
                    (Cols 1 0 0)
                    (Pos 1 2)
                    CommitOK
                    (Pos 1 3)
                    CommitCancel
                )
            )
        )
    )
)

(Layout Content
    (Components
        (Label Label1)
        (CheckButton CheckButton1)
        (Label Label2)
        (InputPanel InputPanel1)
    )
    (Resources
        (Label1.Label "Search in subfolders")
        (Label1.AttachLeft True)
        (Label1.TopOffset 0)
        (Label1.BottomOffset 2)
        (Label1.LeftOffset 0)
        (Label1.RightOffset 4)
        (CheckButton1.Set 1)
        (CheckButton1.AttachLeft True)
        (CheckButton1.TopOffset 0)
        (CheckButton1.BottomOffset 2)
        (CheckButton1.LeftOffset 3)
        (CheckButton1.RightOffset 0)
        (Label2.Label "Syffix BOM")
        (Label2.AttachLeft True)
        (Label2.TopOffset 2)
        (Label2.BottomOffset 0)
        (Label2.LeftOffset 0)
        (Label2.RightOffset 4)
        (InputPanel1.Value "")
        (InputPanel1.TopOffset 2)
        (InputPanel1.BottomOffset 0)
        (InputPanel1.LeftOffset 3)
        (InputPanel1.RightOffset 0)
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.TopOffset 16)
        (.BottomOffset 16)
        (.LeftOffset 10)
        (.RightOffset 10)
        (.ResourceHints "Template:OKCancelDialog.Content")
        (.AttachBottom True)
        (.Layout
            (Grid
                (Rows 0 0)
                (Cols 0 1)
                Label1 CheckButton1 Label2 InputPanel1
            )
        )
    )
)
